[[injections]]
match = "pydicom__pydicom-1413"
enabled = false
content = """
Additional binary VRs are OL, OV, and OD, etc.
"""
# comments = """
# Info available here:
# https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html
# or
# https://pydicom.github.io/pydicom/stable/guides/element_value_types.html
# """

[[injections]]
match = "pylint-dev__astroid-1196"
enabled = false
content = """
When infering, use `safe_infer` imported from `astroid.helpers`, then check if Dict.

Important: Place imports INSIDE the function that you are editing itself. Anywhere else will cause a circular import error.

Here is the function itself.
```py
def safe_infer(node, context=None):
    \"""Return the inferred value for the given node.

    Return None if inference failed or if there is some ambiguity (more than
    one node has been inferred).
    \"""
    try:
        inferit = node.infer(context=context)
        value = next(inferit)
    except (InferenceError, StopIteration):
        return None
    try:
        next(inferit)
        return None  # None if there is ambiguity on the inferred node
    except InferenceError:
        return None  # there is some kind of ambiguity
    except StopIteration:
        return value
```
"""
